### ISSUE TITLE
Does not seem to work with VS Version 17.12.0 Preview 5.0

### ISSUE THREAD

**Issue by TwentyFourMinutes** [Natestah/BlitzVisualStudioExtension#1]
When I click `Blitz Search This` from the Tool bar, nothing happens. There is no window opening or similar. If there is any way for me to get some logs for this extension, please let me know :)

Thanks for you work! Search looks great from the screenshot! :)

**Comment by Natestah** [comment]
Try and download the installer for executable from
https://natestah.com/download

**Comment by Natestah** [comment]
Any luck with that?

**Comment by TwentyFourMinutes** [comment]
@Natestah Sorry for the late reply, only came around to checking it now. I downloaded the .exe which indeed opens. However through the latest version of the VS Extension nothing happens.

**Comment by Natestah** [comment]
Thank you for trying that, I'll give it a go on 17.20.0 Preview today and see if I can reproduce this.

**Comment by Natestah** [comment]
@TwentyFourMinutes I upgraded to that, and It worked for me.  However I did Identify one case were the command would happily do nothing when there is no active document,  this issue is fixed in 1.94 of the Blitz Search Extension. Please update and see if this resolves for you

**Comment by TwentyFourMinutes** [comment]
@Natestah You nailed it, that was the issue. Thank you so much for your time and the extension :)
